CREATE TABLE IF NOT EXISTS employee
(
    id BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    code VARCHAR(36) NOT NULL,
    name VARCHAR(255) NOT NULL,
    daily_value DECIMAL(12, 9) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

CREATE TABLE IF NOT EXISTS advance_money
(
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    value DECIMAL (19, 2) NOT NULL,
    description VARCHAR(255) NOT NULL,
    employee_id BIGINT NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

CREATE TABLE IF NOT EXISTS benefits
(
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    value DECIMAL (19, 2) NOT NULL,
    description VARCHAR(255) NOT NULL,
    employee_id BIGINT NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

CREATE TABLE IF NOT EXISTS withdraw
(
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    value DECIMAL (19, 2) NOT NULL,
    employee_id BIGINT NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

#CHANGING
ALTER TABLE advance_money
    ADD CONSTRAINT FK_ADVANCE_MONEY_ON_EMPLOYEE
    FOREIGN KEY (employee_id) REFERENCES employee (id);

ALTER TABLE benefits
    ADD CONSTRAINT FK_BENEFITS_ON_EMPLOYEE
    FOREIGN KEY (employee_id) REFERENCES employee (id);

ALTER TABLE withdraw
    ADD CONSTRAINT FK_WITHDRAW_ON_EMPLOYEE
    FOREIGN KEY (employee_id) REFERENCES employee (id);